## Assignment 1: NumPy Arrays and Matrix Operations

Objective

Practice using NumPy to create and manipulate multidimensional arrays and perform mathematical and linear-algebra operations.

This assignment is based on the NumPy concepts demonstrated in class: array creation, array properties, slicing, Boolean indexing, element-wise operations, matrix multiplication, transpose, and axis operations.

Instructions

Complete all problems using NumPy. Do not use Python lists for the mathematical operations.
Submit a Jupyter Notebook containing:

* Your Python code
* The output of each problem
* Short answers to the questions
* Clear comments explaining your code

---
#### Part 1 — Creating and Inspecting Arrays

1.	Create the following NumPy array:
```python
 	[[10, 20, 30, 40],
 [50, 60, 70, 80],
 [90, 100, 110, 120]]
```

In [1]:
import numpy as np

arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])

2.	Print:
* The array
* Its type
* Shape
* Number of elements
* Number of dimensions
* Data type

In [2]:
print("The array :\n", arr)
print("Its type :", type(arr))
print("Shape:", arr.shape)
print("Number of elements :", arr.size)
print("Number of dimensions :", arr.ndim)
print("Data type :", arr.dtype)

The array :
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
Its type : <class 'numpy.ndarray'>
Shape: (3, 4)
Number of elements : 12
Number of dimensions : 2
Data type : int64


3.	Create:
* A 3 × 4 array of zeros
* A 2 × 5 array of ones
* A 4 × 4 identity matrix
* A 3 × 3 array of random numbers between 0 and 1

In [3]:
zeros_arr = np.zeros((3, 4))
ones_arr = np.ones((2, 5))
identity_matrix = np.eye(4)
random_arr = np.random.rand(3, 3)

---
## Part 2 — Indexing and Slicing

Using the array from Part 1:

1.	Extract the value 70.
2.	Extract the first row.
3.	Extract the last row.
4.	Extract the second column.
5.	Extract the first three columns.
6.	Extract the last two rows.
7.	Extract every other element from the second row.
8.	Extract the following submatrix:
```python 	
    [[60, 70],
 [100, 110]]
 ```


In [ ]:
print(arr[1, 2])
print(arr[0, :])
print(arr[-1, :])
print(arr[:, 1])
print(arr[:, :3])
print(arr[-2:, :])
print(arr[1, ::2])
print(arr[1:3, 1:3])

1. Value 70: 70
2. First row: [10 20 30 40]
3. Last row: [ 90 100 110 120]
4. Second column: [ 20  60 100]
5. First three columns:
 [[ 10  20  30]
 [ 50  60  70]
 [ 90 100 110]]
6. Last two rows:
 [[ 50  60  70  80]
 [ 90 100 110 120]]
7. Every other element from 2nd row: [50 70]
8. Submatrix:
 [[ 60  70]
 [100 110]]


---
## Part 3 — Boolean Indexing

Create:
```python
x = np.array([[12, 5, 18, 3],
              [25, 7, 14, 9],
              [2, 30, 11, 20]])
```
1.	Extract all values greater than 15.
2.	Extract all values less than or equal to 10.
3.	Replace every value greater than 20 with 0.
4.	Count how many values are greater than 15.

In [5]:
x = np.array([[12, 5, 18, 3],
              [25, 7, 14, 9],
              [2, 30, 11, 20]])

print(x[x > 15])
print(x[x <= 10])

x_modified = x.copy()
x_modified[x_modified > 20] = 0
print(x_modified)

print(np.sum(x > 15))

[18 25 30 20]
[5 3 7 9 2]
[[12  5 18  3]
 [ 0  7 14  9]
 [ 2  0 11 20]]
4


---
## Part 4 — Element-Wise Arithmetic
Create:
```python
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])
```
Calculate:
1.	A + B
2.	A - B
3.	A * B
4.	A / B
5.	A ** 2
6.	np.sqrt(A)

In [6]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print(A + B)
print(A - B)
print(A * B)
print(A / B)
print(A ** 2)
print(np.sqrt(A))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[ 1  4]
 [ 9 16]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


---
## Part 5 — Matrix Multiplication
Create:
```python
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])
```
1.	Compute A @ B.
2.	Compute the same result using np.dot(A, B).
3.	Verify that both results are identical.
4.	Print the shape of A, B, and the result.

The notebook demonstrates the equivalence of .dot(), np.dot(), and @ for matrix multiplication.

In [7]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

print(A @ B)
print(np.dot(A, B))
print(np.array_equal(A @ B, np.dot(A, B)))
print(f"A: {A.shape}, B: {B.shape}, Result: {(A @ B).shape}")


[[ 58  64]
 [139 154]]
[[ 58  64]
 [139 154]]
True
A: (2, 3), B: (3, 2), Result: (2, 2)


---
## Part 6 — Transpose and Axis Operations
Using:
```python
X = np.array([[2, 4, 6],
              [8, 10, 12]])
```
Calculate:
1.	X.T
2.	np.transpose(X)
3.	np.sum(X)
4.	np.sum(X, axis=0)
5.	np.sum(X, axis=1)
6.	np.mean(X)
7.	np.mean(X, axis=0)
8.	np.mean(X, axis=1)
9.	np.max(X, axis=0)
10.	np.min(X, axis=1)
11.	np.std(X)

For each axis operation, write one sentence explaining what the axis represents.

In [10]:
X = np.array([[2, 4, 6],
              [8, 10, 12]])

print(X.T)
print(np.transpose(X))
print(np.sum(X))
print(np.sum(X, axis=0)) # axis=0 represents operations down the columns (vertically across rows).
print(np.sum(X, axis=1)) # axis=1 represents operations across the rows (horizontally across columns)
print(np.mean(X))
print(np.mean(X, axis=0)) # Calculates mean for each column across rows.
print(np.mean(X, axis=1)) # Calculates mean for each row across columns.
print(np.max(X, axis=0)) # Finds maximum element in each column.
print(np.min(X, axis=1)) # Finds minimum element in each row.
print(np.std(X))

[[ 2  8]
 [ 4 10]
 [ 6 12]]
[[ 2  8]
 [ 4 10]
 [ 6 12]]
42
[10 14 18]
[12 30]
7.0
[5. 7. 9.]
[ 4. 10.]
[ 8 10 12]
[2 8]
3.415650255319866


---
## Part 7 — Mini Application: Student Grades

Create a NumPy array containing the grades of 5 students in 4 assignments:

* Student 1: 85, 90, 78, 92
* Student 2: 70, 88, 91, 76
* Student 3: 95, 93, 89, 97
* Student 4: 60, 72, 68, 75
* Student 5: 88, 84, 90, 86

Using NumPy only:
1.	Calculate each student’s average.
2.	Find the highest grade on each assignment.
3.	Find the average grade for each assignment.
4.	Find the student with the highest overall average.
5.	Find all grades below 70.
6.	Replace grades below 70 with 70.
7.	Calculate the overall class average.

In [12]:
grades = np.array([
    [85, 90, 78, 92], 
    [70, 88, 91, 76], 
    [95, 93, 89, 97], 
    [60, 72, 68, 75], 
    [88, 84, 90, 86] 
])

print(np.mean(grades, axis=1))
print(np.max(grades, axis=0))
print(np.mean(grades, axis=0))
print(np.argmax(np.mean(grades, axis=1)))
print(grades[grades<70])
grades_updated = grades.copy()
grades_updated[grades_updated < 70] = 70
print(grades_updated)
print(np.mean(grades))

[86.25 81.25 93.5  68.75 87.  ]
[95 93 91 97]
[79.6 85.4 83.2 85.2]
2
[60 68]
[[85 90 78 92]
 [70 88 91 76]
 [95 93 89 97]
 [70 72 70 75]
 [88 84 90 86]]
83.35


---
## Short Questions

Answer in your own words:
1.	What is the difference between shape, size, and ndim?
2.	What is the difference between element-wise multiplication and matrix multiplication?
3.	What does axis=0 mean for a two-dimensional array?
4.	What does axis=1 mean?
5.	Why is NumPy useful for machine learning and deep learning?


1. shape is a tuple representing the dimesions of array. size is the total number of elements contained in the array. ndim is the number of dimensions of the array.
2. element-wise multiplication multiplies corresponding elements at the same positions in two arrays of the same shape. matrix multiplication performs standard linear algebra matrix multiplication, requiring the number of columns in the first matrix to match the number of rows in the second matrix.
3. It means the first axis(rows)
4. It means the second axis(columns)
5. It makes mathematical computations much faster than standard Python lists because it is written in C. 

---
## Challenge Problem

Create a random 5 × 5 matrix containing integers from 1 to 100.

Using NumPy only:
1.	Find the largest value.
2.	Find the smallest value.
3.	Calculate the mean.
4.	Calculate the standard deviation.
5.	Find all values greater than the mean.
6.	Replace all values below the mean with 0.
7.	Calculate the sum of each row and each column.

In [13]:
matrix = np.random.randint(1, 101, size=(5, 5))
print(matrix)

print(np.max(matrix))
print(np.min(matrix))
print(np.mean(matrix))
print(np.std(matrix))
print(matrix[matrix>np.mean(matrix)])
matrix_updated = matrix.copy()
matrix_updated[matrix_updated < np.mean(matrix)] = 0
print(np.sum(matrix, axis=1))
print(np.sum(matrix, axis=0))

[[92  4  3 75 55]
 [49 92 34 11 74]
 [15 82 60 66 48]
 [ 8 45 46 82 76]
 [82 15 70 31  6]]
92
3
48.84
29.586050767211226
[92 75 55 49 92 74 82 60 66 82 76 82 70]
[229 260 271 257 204]
[246 238 213 265 259]
