# Assignment 2 — PyTorch Tensors and Automatic Differentiation
#### Objective

Practice working with PyTorch tensors, including tensor creation, tensor properties, indexing, slicing, arithmetic, matrix operations, NumPy conversion, GPU awareness, and automatic differentiation.

The assignment follows the concepts demonstrated in the provided PyTorch notebook, including tensor dtype, shape, number of elements, dimensions, GPU availability, requires_grad, backward(), and NumPy/tensor conversion.

---

Instructions

Use PyTorch for all tensor operations.

Begin your notebook with:
```python
import torch
import numpy as np
```

Do not use TensorFlow for this assignment.

For each problem:

* Include your Python code.
* Display the output.
* Add explanations where requested.
* Your notebook should run from beginning to end without errors.

---

#### Part 1 — Creating Tensors

Create the following PyTorch tensors:

1. Scalar


In [2]:
import torch
import numpy as np

# TODO: Create a scalar tensor containing: 5

print(torch.tensor(5))


tensor(5)


2. Floating-point scalar

In [3]:
# TODO: Create a scalar tensor containing:
print(torch.tensor(5.0))

tensor(5.)


3. Vector

In [4]:
# TODO: Create: [1, 2, 3, 4, 5]
print(torch.tensor([1,2,3,4,5]))

tensor([1, 2, 3, 4, 5])


4. Matrix

Create:
```python
[[1, 2, 3],
 [4, 5, 6]]
```

In [5]:
# TODO: Create: [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
print(torch.tensor([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]))

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])


5. Three-dimensional tensor

Create a tensor with shape: 3 × 2 × 2

In [6]:
# TODO: create tensor 3x2x2
print(torch.zeros(3,2,2))

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])


---

#### Part 2 — Tensor Properties

Create:
```python
x = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.]])
```

In [7]:
# TODO: create the tensor
x = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.]])

Determine:

* Its shape
* Number of dimensions
* Number of elements
* Data type

In [8]:
# TODO: determine shape, dimentions, number of elements, data type
print(x.shape)
print(x.ndim)
print(x.numel)
print(x.dtype)

torch.Size([2, 3])
2
<built-in method numel of Tensor object at 0x00000200F245BAD0>
torch.float32


Question 1

What is the difference between:

* shape
* ndim
* numel()
* dtype

1. shape returns the size of the tensor along eaxh dimension
2. ndim returns the number of tensor dimensions
3. numel() returns the total number of elements in the tensor
4. dtype specifies the data type of the elements

Question 2

Why does the tensor have:
```python
2 dimensions
6 elements
```
even though its shape is: (2, 3)

---

The shape(2,3) specifies that there are 2 rows and 3 columns. Since there are 2 axes, the ndim is 2. Since there are 2 rows wirh 3 elements each, the numel() is 6.

#### Part 3 — Creating Special Tensors

Using PyTorch, create and display:

1. Zeros

A 2 × 3 tensor containing zeros.

In [9]:
# TODO: 2x3 zeros:
print(torch.zeros(2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])


2. Ones

A 3 × 3 tensor containing ones.

In [45]:
# TODO: Create 3x3 ones tensor
print(torch.ones(3,3))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


3. Identity matrix

In [46]:
# TODO: A 4 × 4 identity matrix.
print(torch.eye(4))

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


4. Range

Create a tensor containing:

0, 1, 2, 3, ..., 9

In [48]:
# TODO: Create range tensor from 0 to 9
print(torch.arange(10))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


5. Random tensor

Create a 3 × 3 tensor containing random values between 0 and 1.

In [49]:
# TODO: 3x3 random tensor between 0 and 1
print(torch.rand(3,3))

tensor([[0.4986, 0.0692, 0.4617],
        [0.6731, 0.8586, 0.8581],
        [0.9059, 0.5474, 0.1553]])


---
#### Part 4 — Indexing and Slicing

Create:
```python
x = torch.tensor([[10, 20, 30, 40],
                  [50, 60, 70, 80],
                  [90, 100, 110, 120]])
```
Using PyTorch indexing and slicing:


In [51]:
x = torch.tensor([[10, 20, 30, 40],
                  [50, 60, 70, 80],
                  [90, 100, 110, 120]])

# TODO: 1. Extract 70
print(x[1,2].item())

70


In [54]:
# TODO: 2. Extract the first row
print(x[0, :])

tensor([10, 20, 30, 40])


In [55]:
# TODO: 3. Extract the last row
print(x[-1, :])

tensor([ 90, 100, 110, 120])


In [56]:
# TODO: 4. Extract the second column
print(x[:, 1])

tensor([ 20,  60, 100])


In [57]:
# TODO: 5. Extract the last two rows
print(x[-2:, :])

tensor([[ 50,  60,  70,  80],
        [ 90, 100, 110, 120]])


In [58]:
# TODO: 6. Extract the first three columns
print(x[:, :3])

tensor([[ 10,  20,  30],
        [ 50,  60,  70],
        [ 90, 100, 110]])


In [59]:
# TODO: 7.Extract: [[60, 70], [100, 110]]
print(x[1:3, 1:3])

tensor([[ 60,  70],
        [100, 110]])


Question

Explain how PyTorch tensor indexing is similar to NumPy array indexing.



Both use zero-based indexing, comma-separated dimension selectors [row,col], negative indexing for accessing elements from the end, and standard slicing syntax(start:stop:step).

---
#### Part 5 — Tensor Arithmetic

Create:
```python
A = torch.tensor([[1., 2.],
                  [3., 4.]])

B = torch.tensor([[5., 6.],
                  [7., 8.]])
```

In [60]:
A = torch.tensor([[1., 2.],
                  [3., 4.]])

B = torch.tensor([[5., 6.],
                  [7., 8.]])

# TODO: Calculate A+B
print(A + B)

tensor([[ 6.,  8.],
        [10., 12.]])


In [61]:
# TODO: Calculate A-B
print(A - B)

tensor([[-4., -4.],
        [-4., -4.]])


In [62]:
# TODO: Calculate A*B
print(A * B)

tensor([[ 5., 12.],
        [21., 32.]])


In [63]:
# TODO: Calculate A/B
print(A / B)

tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


In [64]:
# TODO: Calculate A to the power 2
print(A ** 2)

tensor([[ 1.,  4.],
        [ 9., 16.]])


In [65]:
# TODO: Calculate square root of A
print(torch.sqrt(A))

tensor([[1.0000, 1.4142],
        [1.7321, 2.0000]])


7. Matrix multiplication

In [66]:
# TODO: Calculate matrix multiplicaton of A and B in two ways
# Verify that the results are identical.
print(A@B)
print(torch.matmul(A,B))
print(torch.equal(A@B, torch.matmul(A,B)))

tensor([[19., 22.],
        [43., 50.]])
tensor([[19., 22.],
        [43., 50.]])
True


Question

Explain the difference between:
```python
A * B
and:
A @ B
```

A*B performs element-wise multiplication, which each corresponding element of A and B is multiplied individually. A@B performs matrix multiplication.

---

Part 6 — Matrix Operations and Reductions

Create:
```python
A = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.]])

Perform the following operations.
```
1. Transpose

In [67]:
# TODO: transpose of A
A = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.]])
print(A.T)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [68]:
# TODO: sum all elements of A along dimension 0
print(torch.sum(A, dim=0))

tensor([5., 7., 9.])


In [69]:
# TODO: sum all elements of A along dimension 1
print(torch.sum(A, dim=1))

tensor([ 6., 15.])


In [70]:
# TODO: Calculate the mean of all elements.
print(torch.mean(A))

tensor(3.5000)


In [71]:
# TODO: Calculate the maximum of all elements.
print(torch.max(A))

tensor(6.)


In [72]:
# TODO: Calculate the minimum of all elements.
print(torch.min(A))

tensor(1.)


In [73]:
# TODO: Calculate the standard deviation of all elements.
print(torch.std(A))

tensor(1.8708)


Questions

Explain:

* What does dim=0 mean?
* What does dim=1 mean?
* Why does reducing along a dimension change the shape of the tensor?

1. dim=0 means rows
2. dim=1 means columns
3. That's because the operation aggregeates all values along that targeted dimension into a single summary value, effectively removing that dimension from the resulting tensor shape.

---
Part 7 — NumPy ↔ PyTorch

Create the following NumPy array:
```python
a = np.array([[1., 2.],
              [3., 4.]])
```

In [74]:
# TODO: Convert the NumPy array into a PyTorch tensor.
a = np.array([[1., 2.],
              [3., 4.]])
A= torch.from_numpy(a)

In [75]:
# TODO: print tensor A, shape and data type
print(A)
print(A.shape)
print(A.dtype)

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
torch.Size([2, 2])
torch.float64


In [76]:
# TODO: Add 10 to the A tensor
print(A + 10)

tensor([[11., 12.],
        [13., 14.]], dtype=torch.float64)


In [77]:
# TODO: Convert the resulting tensor back into a NumPy array.
print((A+10).numpy())

[[11. 12.]
 [13. 14.]]


In [78]:
# TODO: Verify that the resulting object is a NumPy array.
print(type((A+10).numpy()))
print(isinstance((A+10).numpy(), np.ndarray))

<class 'numpy.ndarray'>
True


In [ ]:
)

---
Part 8 — GPU Awareness

In [79]:
# TODO: Determine whether a GPU is available:
print(torch.cuda.is_available())

False


In [80]:
# TODO: Create a device:
print(torch.device("cuda" if torch.cuda.is_available() else "cpu"))

cpu


In [81]:
# Create a tensor:
x = torch.tensor([[1., 2.],
                  [3., 4.]])

# TODO: Move it to the selected device:
x_device = x.to(torch.device("cuda" if torch.cuda.is_available() else "cpu"))


Questions
* What device is your tensor using?
* What is the difference between CPU and GPU computation?
* Why are GPUs useful for deep learning?
* What happens if CUDA is not available?

1. It uses cpu
2. CPUs excel at sequential processing with a few powerful cores, whereas GPUs contain thousands of smaller cores designed for massive parallel processing.


---
Part 9 — Automatic Differentiation

PyTorch provides automatic differentiation using autograd.

In [82]:
x = torch.tensor([[1., 2.],
                  [3., 4.]], requires_grad=True)

# TODO: Calculate y = 3x² + 2
y = 3 * (x ** 2) + 2



In [83]:
# Then calculate:
z = torch.sum(y)

# Use:
z.backward()
# to calculate: dz/dx

# Print:

print(y)
print(z)
print(x.grad)


tensor([[ 5., 14.],
        [29., 50.]], grad_fn=<AddBackward0>)
tensor(98., grad_fn=<SumBackward0>)
tensor([[ 6., 12.],
        [18., 24.]])


Questions
* What does requires_grad=True mean?
* What does backward() do?
* What is stored in x.grad?
* Why is automatic differentiation important for neural networks?

1. It tells Pytorch to track all computational operations performed on this tensor so that gradients can be automatically calculated during backpropagation.
2. It initiates the backpropagation process, computing the partial derivatives of the scalar output z.
3. It stores the calculated gradient values dz/dx.
4. It allows model weights and parameters to update automatically without manual gradient derivation.